# Generated by Django 3.1.6 on 2021-02-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='category',
            name='tg_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tg_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
