# Generated by Django 3.1.6 on 2021-03-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20210226_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewed',
        ),
    ]
