# Generated by Django 3.1.6 on 2021-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_remove_product_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
