# Generated by Django 3.1.6 on 2021-06-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_orderproduct_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='phone_number',
        ),
    ]
