# Generated by Django 3.1.6 on 2021-06-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_remove_tguser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Заказанный продукт', 'verbose_name_plural': 'Заказанные продукты'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='tg_user',
        ),
    ]
